import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Lincoln",
      email: "lincoln.kantet@gmail.com",
      password: bcrypt.hashSync("1234", 8),

      isAdmin: true,
    },
    {
      name: "Customer",
      email: "kantet@gmail.com",
      password: bcrypt.hashSync("12345", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "no name",
      category: "T-sht",
      image: "/images/img.png",
      price: 120,
      countInStock: 20,
      brand: "Nik",
      rating: 1,
      numReviewes: 12,
      description: "High quality product",
    },
    {
      name: " Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.png",
      countInStock: 10,
      price: 10,
      brand: "Nike",
      rating: 3,
      numReviewes: 7,
      description: "High quality product",
    },
    {
      name: "Nike Slinmm T-shirt",
      category: "Tshirt",
      image: "/images/img.png",
      price: 120,
      countInStock: 0,
      brand: "Ninnke",
      rating: 4.5,
      numReviewes: 10,
      description: "High sdsdquality product",
    },
    {
      name: "Nike Slinnjm T-shirt",
      category: "T-shjnjkirt",
      image: "/images/img.png",
      price: 12,
      countInStock: 5,
      brand: "Nilkke",
      rating: 4,
      numReviewes: 10,
      description: "High edfdsquality product",
    },
    {
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.png",
      price: 120,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviewes: 10,
      description: "High qualityxcs product",
    },
    {
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.png",
      price: 1200,
      brand: "Nike",
      rating: 5,
      numReviewes: 0,
      description: "High quality product",
    },
    {
      name: "Nike Slim T-shirt",
      category: "T-shirt",
      image: "/images/img.png",
      price: 1200,
      brand: "Nike",
      rating: 1.5,
      numReviewes: 1,
      description: "High kkquality product",
    },
  ],
};
export default data;
