const CONSTANTS = {
  products: {
    PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
    PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
    PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",
  },
  product: {
    PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",
    // Create new products
    PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
    PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
    PRODUCT_CREATE_FAIL: "PRODUCT_CREATE_FAIL",
    PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",

    PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
    PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
    PRODUCT_UPDATE_FAIL: "PRODUCT_UPDATE_FAIL",
    PRODUCT_UPDATE_RESET: "PRODUCT_UPDATE_RESET",

    PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
    PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
    PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",
    PRODUCT_DELETE_RESET: "PRODUCT_DELETE_RESET",
  },
  cart: {
    CART_EMPTY: "CART_EMPTY",
    CART_ADD_ITEM: "CART_ADD_ITEM",
    CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
    SAVE_SHIPPING_ADDRESS: "SAVE_SHIPPING_ADDRESS",
    CART_SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",
  },
  user: {
    // create user
    USER_SIGNIN_REQUEST: "USER_SIGNIN_REQUEST",
    USER_SIGNIN_SUCCESS: "USER_SIGNIN_SUCCESS",
    USER_SIGNIN_FAIL: "USER_SIGNIN_FAIL",
    USER_SIGNIN_SIGNOUT: "USER_SIGNIN_SIGNOUT",
    // register user
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
    // REQUEST profile
    USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
    USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
    USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
    // update profile
    USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
    USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS ",
    USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
    USER_UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",
  },
  order: {
    ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
    ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
    ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
    ORDER_CREATE_RESET: "ORDER_CREATE_RESET",

    ALL_ORDERS_LIST_REQUEST: "ORDER_LIST_REQUEST",
    ALL_ORDERS_LIST_FAIL: "ORDER_LIST_FAIL",
    ALL_ORDERS_LIST_SUCCESS: "ORDER_LIST_SUCCESS",

    ORDER_DELETE_REQUEST: "ORDER_DELETE_REQUEST",
    ORDER_DELETE_SUCCESS: "ORDER_DELETE_SUCCESS",
    ORDER_DELETE_FAIL: "ORDER_DELETE_FAIL",
    ORDER_DELETE_RESET: "ORDER_DELETE_RESET",

    ORDER_DELIVER_REQUEST: "ORDER_DELIVER_REQUEST",
    ORDER_DELIVER_SUCCESS: "ORDER_DELIVER_SUCCESS",
    ORDER_DELIVER_FAIL: "ORDER_DELIVER_FAIL",
    ORDER_DELIVER_RESET: "ORDER_DELIVER_RESET",
  },
  orderDetails: {
    ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
    ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
    ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",
  },
  orderPay: {
    ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
    ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
    ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
    ORDER_PAY_RESET: "ORDER_PAY_RESET",
  },
  myOrders: {
    ORDER_LIST_REQUEST: "ORDER_LIST_REQUEST",
    ORDER_LIST_FAIL: "ORDER_LIST_FAIL",
    ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
  },
};

export default CONSTANTS;
